 .buttonCls{
            margin-left: 3px;
            margin-right: 3px;
            padding: 4px 3px;
            color: #333;
            margin: 1px;
            border: 1px solid #B5B5B5;
            border-bottom-color: #7F7F7F;
            background-color: transparent;
            font-weight: bold;
            font-size: .9em;
            -webkit-border-radius: 3px;
            border-radius: 3px;
            text-decoration:none;
        }