// ----------------------------------------------------------------------------------
// This class is used for save the Event Start And End Time
// Version#        Date             Author              Description
// ----------------------------------------------------------------------------------
//   1.0       15 April 2015      Ashutosh Kumar        Initial Version
// ----------------------------------------------------------------------------------
// ----------------------------------------------------------------------------------
//
// ----------------------------------------------------------------------------------
// 
//
public class Saasfocus_EventClass
   {
   public String Email;
   public String StartDateTime;
   public String EndDateTime;
   }