{
  "statusCode": 200,
  "error": null,
  "message": null,
  "meta": {
    "api_version": "1.0.0",
    "community": "ACF"
  },
  "data": {
    "documents": [
      {
        "key": "ffab49ad-15de-4b08-9ff3-2e623153f9a5",
        "version": "CK3pm4T6hCkbjsA8KE90wlxl8GX6OdXu"
      },
      {
        "key": "e8c9cac4-4d9c-41c5-abed-1ad0b792db07",
        "version": "IMT7Ol2V6mQH.l1xi9uZN0kw5gqDZXPj"
      }
    ]
  }
}